version: "3.9"

services:
  content-notification:
    build:
      context: .
    container_name: content-notification
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

