spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_COLLECTION}
      uri: ${DB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  jackson:
    default-property-inclusion: non_null

notification:
  email:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

telegram:
  bot:
    token: ${TG_BOT_TOKEN}

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
